### PR TITLE
Fixes some typos

### PR DESCRIPTION
**Pull request by danburzo**
Hi there, I hope this doesn't come off as heavy-handed, but as I was reading the document I noticed a few typos and I thought I'd make a PR with them. Hope I got them right!

### CODE REVIEW

**Comment by plinss** [comment]
LGTM

**Comment by danburzo** [comment]
I'm cleaning up my repos and I noticed I still have a fork for this. The changes seem low-impact, but I'm okay with not merging the PR, but in any case I'd like to delete my fork soon :-)

**Comment by dbaron** [comment]
I'm not 100% convinced all of the changes are *needed*, but they at least all seem fine, and many are clearly improvements, so I'll merge this.

**Comment by danburzo** [comment]
Thanks, @dbaron!

**Pull request merged**
